name: shareplate
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  firebase_core: ^2.24.2
  google_sign_in: ^6.2.1
  firebase_auth: ^4.16.0
  introduction_screen: ^3.1.12
  intl_phone_field: ^3.2.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    
  fonts:
    - family : Montserrat
      fonts : 
      - asset : assets/fonts/Montserrat-Regular.ttf
      - asset : assets/fonts/Montserrat-Medium.ttf
        weight : 500
      - asset : assets/fonts/Montserrat-SemiBold.ttf
        weight : 600
      - asset : assets/fonts/Montserrat-Bold.ttf
        weight : 700

    - family : Amaranth
      fonts :
        - asset : assets/fonts/Amaranth-Regular.ttf 

