// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxxDRMP90NLxXjgQqm1PeDG-z3zVqQUMg',
    appId: '1:948615999236:web:79e3b14035309e4bd3aa51',
    messagingSenderId: '948615999236',
    projectId: 'shareplate-7c907',
    authDomain: 'shareplate-7c907.firebaseapp.com',
    storageBucket: 'shareplate-7c907.appspot.com',
    measurementId: 'G-HMQXL51N0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5viZRDj_Jf9LzzXmlQby-Nl-SJ77tc7E',
    appId: '1:948615999236:android:a73ef590aab955f3d3aa51',
    messagingSenderId: '948615999236',
    projectId: 'shareplate-7c907',
    storageBucket: 'shareplate-7c907.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWPHlTmTNlgnl3te6YCEyO0-MItuBQwo0',
    appId: '1:948615999236:ios:201acceadc4c1e33d3aa51',
    messagingSenderId: '948615999236',
    projectId: 'shareplate-7c907',
    storageBucket: 'shareplate-7c907.appspot.com',
    iosBundleId: 'com.bismillahmsib.shareplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWPHlTmTNlgnl3te6YCEyO0-MItuBQwo0',
    appId: '1:948615999236:ios:d5de93f8f5c859a3d3aa51',
    messagingSenderId: '948615999236',
    projectId: 'shareplate-7c907',
    storageBucket: 'shareplate-7c907.appspot.com',
    iosBundleId: 'com.bismillahmsib.shareplate.RunnerTests',
  );
}
